// ========================================
// NATIONAL TARGETS - 30 HIGH-VALUE ZONES
// Expert Panneau Solaire - Couverture Nationale pSEO
// ========================================

export interface NationalTarget {
    slug: string;
    name: string;
    heroTitle: string;
    geo: { lat: number; lng: number };
    /** Zones d'intervention réelles : communes limitrophes (source Wikidata / données communales suisses) */
    top_places: string[];
    zip: string;
    tier: 'BIG5' | 'GOLDEN' | 'HUB' | 'STRATEGIC';
    heroImage?: string;
    unique_intro?: string;
    /** Communes limitrophes réelles avec distance calculée depuis les coordonnées officielles */
    zones?: { nom: string; km: number }[];
}

export const NATIONAL_TARGETS: NationalTarget[] = [
    {
        slug: "geneve",
        name: "Genève",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.20456, lng: 6.14246 },
        top_places: ["Carouge", "Lancy", "Vernier", "Cologny"],
        zip: "1201",
        tier: 'BIG5',
        unique_intro: "À Genève et dans les communes du canton, les toitures bien exposées et le fort ensoleillement du bassin lémanique rendent le photovoltaïque particulièrement rentable. Nos installateurs partenaires étudient votre toiture, dimensionnent l'installation et montent le dossier de rétribution unique auprès de Pronovo.",
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Carouge", km: 2.6 }, { nom: "Lancy", km: 2.6 }, { nom: "Vernier", km: 3.3 }, { nom: "Cologny", km: 3.4 }],
    },
    {
        slug: "lausanne",
        name: "Lausanne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.52865, lng: 6.63852 },
        top_places: ["Le Mont-sur-Lausanne", "Pully", "Prilly", "Épalinges"],
        zip: "1003",
        tier: 'BIG5',
        unique_intro: "À Lausanne et dans le canton de Vaud, la rétribution unique de Pronovo et les programmes cantonaux soutiennent l'autoconsommation solaire. Nos partenaires réalisent l'étude de toiture, le dimensionnement et la mise en service de votre centrale photovoltaïque.",
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Le Mont-sur-Lausanne", km: 2.4 }, { nom: "Pully", km: 2.5 }, { nom: "Prilly", km: 3.0 }, { nom: "Épalinges", km: 3.2 }],
    },
    {
        slug: "fribourg",
        name: "Fribourg",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.80337, lng: 7.16178 },
        top_places: ["Granges-Paccot", "Marly", "Givisiez", "Pierrafortscha"],
        zip: "1700",
        tier: 'BIG5',
        unique_intro: "Dans le canton de Fribourg, l'ensoleillement et les subventions cantonales complémentaires favorisent les installations photovoltaïques résidentielles. Nos installateurs partenaires vous accompagnent de l'étude à la mise en service, dossier Pronovo inclus.",
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Granges-Paccot", km: 1.7 }, { nom: "Marly", km: 2.3 }, { nom: "Givisiez", km: 2.6 }, { nom: "Pierrafortscha", km: 2.8 }],
    },
    {
        slug: "neuchatel",
        name: "Neuchâtel",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.02097, lng: 6.94808 },
        top_places: ["Hauterive", "Saint-Blaise", "La Tène", "Laténa"],
        zip: "2000",
        tier: 'BIG5',
        unique_intro: "Dans le canton de Neuchâtel, le potentiel solaire des toitures est élevé et les aides cantonales s'ajoutent à la rétribution unique fédérale. Nos partenaires dimensionnent votre installation solaire et gèrent les démarches administratives.",
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Hauterive", km: 1.5 }, { nom: "Saint-Blaise", km: 3.0 }, { nom: "La Tène", km: 4.5 }, { nom: "Laténa", km: 4.5 }],
    },
    {
        slug: "sion",
        name: "Sion",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.21694, lng: 7.34285 },
        top_places: ["Veysonnaz", "Conthey", "Savièse", "Vex"],
        zip: "1950",
        tier: 'BIG5',
        unique_intro: "En Valais, l'un des cantons les plus ensoleillés de Suisse, une installation photovoltaïque s'amortit souvent en moins de dix ans. Nos partenaires à Sion et dans le Valais romand étudient votre projet et montent le dossier de subvention.",
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Veysonnaz", km: 2.2 }, { nom: "Conthey", km: 3.3 }, { nom: "Savièse", km: 3.7 }, { nom: "Vex", km: 4.4 }],
    },
    {
        slug: "montreux",
        name: "Montreux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.44832, lng: 6.93596 },
        top_places: ["Veytaux", "Blonay – Saint-Légier", "La Tour-de-Peilz", "Villeneuve"],
        zip: "1820",
        tier: 'GOLDEN',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Veytaux", km: 3.1 }, { nom: "Blonay – Saint-Légier", km: 3.7 }, { nom: "La Tour-de-Peilz", km: 5.3 }, { nom: "Villeneuve", km: 5.8 }],
    },
    {
        slug: "vevey",
        name: "Vevey",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.44206, lng: 6.83264 },
        top_places: ["Corseaux", "La Tour-de-Peilz", "Corsier-sur-Vevey", "Saint-Saphorin"],
        zip: "1800",
        tier: 'GOLDEN',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Corseaux", km: 2.7 }, { nom: "La Tour-de-Peilz", km: 2.8 }, { nom: "Corsier-sur-Vevey", km: 3.0 }, { nom: "Saint-Saphorin", km: 3.7 }],
    },
    {
        slug: "yverdon-les-bains",
        name: "Yverdon-les-Bains",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.7681, lng: 6.63288 },
        top_places: ["Montagny-près-Yverdon", "Belmont-sur-Yverdon", "Valeyres-sous-Ursins", "Treycovagnes"],
        zip: "1400",
        tier: 'GOLDEN',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Montagny-près-Yverdon", km: 2.1 }, { nom: "Belmont-sur-Yverdon", km: 2.4 }, { nom: "Valeyres-sous-Ursins", km: 2.4 }, { nom: "Treycovagnes", km: 2.5 }],
    },
    {
        slug: "la-chaux-de-fonds",
        name: "La Chaux-de-Fonds",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.11421, lng: 6.84379 },
        top_places: ["La Ferrière", "Les Planchettes", "Renan", "Val-de-Ruz"],
        zip: "2300",
        tier: 'GOLDEN',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "La Ferrière", km: 5.4 }, { nom: "Les Planchettes", km: 5.5 }, { nom: "Renan", km: 6.4 }, { nom: "Val-de-Ruz", km: 7.8 }],
    },
    {
        slug: "bienne",
        name: "Bienne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.14949, lng: 7.26901 },
        top_places: ["Evilard", "Brügg", "Orpond", "Nidau"],
        zip: "2502",
        tier: 'GOLDEN',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Evilard", km: 2.3 }, { nom: "Brügg", km: 2.7 }, { nom: "Orpond", km: 3.1 }, { nom: "Nidau", km: 3.4 }],
    },
    {
        slug: "sierre",
        name: "Sierre",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.27641, lng: 7.50851 },
        top_places: ["Chalais", "Chippis", "Noble-Contrée", "Crans-Montana"],
        zip: "3960",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Chalais", km: 1.3 }, { nom: "Chippis", km: 2.1 }, { nom: "Noble-Contrée", km: 3.2 }, { nom: "Crans-Montana", km: 4.4 }],
    },
    {
        slug: "martigny",
        name: "Martigny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.10704, lng: 7.10047 },
        top_places: ["Bovernier", "Fully", "Martigny-Combe", "Sembrancher"],
        zip: "1920",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Bovernier", km: 2.9 }, { nom: "Fully", km: 3.2 }, { nom: "Martigny-Combe", km: 4.7 }, { nom: "Sembrancher", km: 5.1 }],
    },
    {
        slug: "nyon",
        name: "Nyon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.38345, lng: 6.23263 },
        top_places: ["Prangins", "Eysins", "Signy-Avenex", "Grens"],
        zip: "1260",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Prangins", km: 2.3 }, { nom: "Eysins", km: 2.5 }, { nom: "Signy-Avenex", km: 2.8 }, { nom: "Grens", km: 3.4 }],
    },
    {
        slug: "morges",
        name: "Morges",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.47904, lng: 6.51307 },
        top_places: ["Lully", "Tolochenaz", "Saint-Prex", "Préverenges"],
        zip: "1110",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Lully", km: 4.2 }, { nom: "Tolochenaz", km: 4.2 }, { nom: "Saint-Prex", km: 4.3 }, { nom: "Préverenges", km: 4.5 }],
    },
    {
        slug: "renens",
        name: "Renens",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.53516, lng: 6.58858 },
        top_places: ["Prilly", "Chavannes-près-Renens", "Crissier", "Jouxtens-Mézery"],
        zip: "1020",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Prilly", km: 0.9 }, { nom: "Chavannes-près-Renens", km: 1.2 }, { nom: "Crissier", km: 1.7 }, { nom: "Jouxtens-Mézery", km: 1.9 }],
    },
    {
        slug: "pully",
        name: "Pully",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.47947, lng: 6.65424 },
        top_places: ["Paudex", "Lutry", "Bourg-en-Lavaux", "Belmont-sur-Lausanne"],
        zip: "1009",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Paudex", km: 3.5 }, { nom: "Lutry", km: 5.2 }, { nom: "Bourg-en-Lavaux", km: 5.3 }, { nom: "Belmont-sur-Lausanne", km: 5.8 }],
    },
    {
        slug: "carouge",
        name: "Carouge",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.17959, lng: 6.14239 },
        top_places: ["Troinex", "Lancy", "Genève", "Plan-les-Ouates"],
        zip: "1227",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Troinex", km: 1.9 }, { nom: "Lancy", km: 2.3 }, { nom: "Genève", km: 2.3 }, { nom: "Plan-les-Ouates", km: 2.4 }],
    },
    {
        slug: "vernier",
        name: "Vernier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.20856, lng: 6.10316 },
        top_places: ["Lancy", "Onex", "Grand-Saconnex", "Confignon"],
        zip: "1214",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Lancy", km: 2.3 }, { nom: "Onex", km: 2.8 }, { nom: "Grand-Saconnex", km: 2.9 }, { nom: "Confignon", km: 3.2 }],
    },
    {
        slug: "lancy",
        name: "Lancy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.18501, lng: 6.11925 },
        top_places: ["Onex", "Carouge", "Plan-les-Ouates", "Vernier"],
        zip: "1212",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Onex", km: 1.5 }, { nom: "Carouge", km: 1.7 }, { nom: "Plan-les-Ouates", km: 2.0 }, { nom: "Vernier", km: 2.2 }],
    },
    {
        slug: "meyrin",
        name: "Meyrin",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23215, lng: 6.07614 },
        top_places: ["Grand-Saconnex", "Satigny", "Vernier", "Collex-Bossy"],
        zip: "1217",
        tier: 'STRATEGIC',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Grand-Saconnex", km: 3.1 }, { nom: "Satigny", km: 3.6 }, { nom: "Vernier", km: 4.0 }, { nom: "Collex-Bossy", km: 4.9 }],
    },
    {
        slug: "onex",
        name: "Onex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.18544, lng: 6.09949 },
        top_places: ["Confignon", "Lancy", "Vernier", "Plan-les-Ouates"],
        zip: "1213",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Confignon", km: 1.3 }, { nom: "Lancy", km: 1.3 }, { nom: "Vernier", km: 1.6 }, { nom: "Plan-les-Ouates", km: 2.5 }],
    },
    {
        slug: "thonex",
        name: "Thônex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.1952, lng: 6.20802 },
        top_places: ["Chêne-Bourg", "Chêne-Bougeries", "Vandœuvres", "Puplinge"],
        zip: "1226",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Chêne-Bourg", km: 0.9 }, { nom: "Chêne-Bougeries", km: 2.3 }, { nom: "Vandœuvres", km: 2.5 }, { nom: "Puplinge", km: 2.5 }],
    },
    {
        slug: "chene-bougeries",
        name: "Chêne-Bougeries",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19202, lng: 6.17772 },
        top_places: ["Chêne-Bourg", "Genève", "Cologny", "Veyrier"],
        zip: "1224",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Chêne-Bourg", km: 1.6 }, { nom: "Genève", km: 2.3 }, { nom: "Cologny", km: 2.8 }, { nom: "Veyrier", km: 2.9 }],
    },
    {
        slug: "le-grand-saconnex",
        name: "Le Grand-Saconnex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23624, lng: 6.11858 },
        top_places: ["Grand-Saconnex", "Pregny-Chambésy", "Bellevue", "Meyrin"],
        zip: "1218",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Grand-Saconnex", km: 0.4 }, { nom: "Pregny-Chambésy", km: 2.0 }, { nom: "Bellevue", km: 2.9 }, { nom: "Meyrin", km: 3.1 }],
    },
    {
        slug: "versoix",
        name: "Versoix",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.29123, lng: 6.15611 },
        top_places: ["Mies", "Tannay", "Genthod", "Chavannes-des-Bois"],
        zip: "1290",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Mies", km: 1.3 }, { nom: "Tannay", km: 2.3 }, { nom: "Genthod", km: 2.8 }, { nom: "Chavannes-des-Bois", km: 3.3 }],
    },
    {
        slug: "gland",
        name: "Gland",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.41051, lng: 6.28794 },
        top_places: ["Bursinel", "Dully", "Prangins", "Begnins"],
        zip: "1196",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Bursinel", km: 2.7 }, { nom: "Dully", km: 2.7 }, { nom: "Prangins", km: 3.1 }, { nom: "Begnins", km: 3.9 }],
    },
    {
        slug: "rolle",
        name: "Rolle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.42596, lng: 6.34889 },
        top_places: ["Bursinel", "Dully", "Gilly", "Mont-sur-Rolle"],
        zip: "1180",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Bursinel", km: 3.8 }, { nom: "Dully", km: 3.8 }, { nom: "Gilly", km: 4.6 }, { nom: "Mont-sur-Rolle", km: 4.7 }],
    },
    {
        slug: "prilly",
        name: "Prilly",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.53825, lng: 6.60459 },
        top_places: ["Renens", "Jouxtens-Mézery", "Crissier", "Lausanne"],
        zip: "1008",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Renens", km: 1.2 }, { nom: "Jouxtens-Mézery", km: 1.4 }, { nom: "Crissier", km: 2.1 }, { nom: "Lausanne", km: 2.3 }],
    },
    {
        slug: "le-locle",
        name: "Le Locle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.05764, lng: 6.74637 },
        top_places: ["La Sagne", "La Chaux-du-Milieu", "Les Planchettes", "Les Ponts-de-Martel"],
        zip: "2400",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "La Sagne", km: 4.5 }, { nom: "La Chaux-du-Milieu", km: 5.8 }, { nom: "Les Planchettes", km: 5.9 }, { nom: "Les Ponts-de-Martel", km: 6.9 }],
    },
    {
        slug: "bulle",
        name: "Bulle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.60516, lng: 7.06694 },
        top_places: ["Le Pâquier", "Broc", "Gruyères", "Riaz"],
        zip: "1630",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Le Pâquier", km: 1.5 }, { nom: "Broc", km: 2.6 }, { nom: "Gruyères", km: 2.7 }, { nom: "Riaz", km: 3.1 }],
    },
    {
        slug: "conthey",
        name: "Conthey",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.26029, lng: 7.28109 },
        top_places: ["Vétroz", "Savièse", "Ardon", "Sion"],
        zip: "1964",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Vétroz", km: 3.9 }, { nom: "Savièse", km: 4.2 }, { nom: "Ardon", km: 7.1 }, { nom: "Sion", km: 7.3 }],
    },
    {
        slug: "monthey",
        name: "Monthey",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.2439, lng: 6.95421 },
        top_places: ["Massongex", "Collombey-Muraz", "Troistorrents", "Vérossaz"],
        zip: "1870",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Massongex", km: 2.3 }, { nom: "Collombey-Muraz", km: 2.6 }, { nom: "Troistorrents", km: 3.1 }, { nom: "Vérossaz", km: 3.8 }],
    },
    {
        slug: "saint-maurice",
        name: "Saint-Maurice",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19619, lng: 7.00536 },
        top_places: ["Lavey-Morcles", "Evionnaz", "Vérossaz", "Collonges"],
        zip: "1890",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Lavey-Morcles", km: 2.2 }, { nom: "Evionnaz", km: 2.3 }, { nom: "Vérossaz", km: 2.8 }, { nom: "Collonges", km: 3.9 }],
    },
    {
        slug: "delemont",
        name: "Delémont",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.37165, lng: 7.33109 },
        top_places: ["Courroux", "Rossemaison", "Mettembert", "Soyhières"],
        zip: "2800",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Courroux", km: 2.7 }, { nom: "Rossemaison", km: 2.8 }, { nom: "Mettembert", km: 3.3 }, { nom: "Soyhières", km: 4.1 }],
    },
    {
        slug: "porrentruy",
        name: "Porrentruy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.42101, lng: 7.0684 },
        top_places: ["Courchavon", "Fontenais", "Courtedoux", "Basse-Allaine"],
        zip: "2900",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Courchavon", km: 1.9 }, { nom: "Fontenais", km: 2.6 }, { nom: "Courtedoux", km: 3.2 }, { nom: "Basse-Allaine", km: 4.2 }],
    },
    {
        slug: "payerne",
        name: "Payerne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.82126, lng: 6.93163 },
        top_places: ["Corcelles-près-Payerne", "Fétigny-Ménières", "Fétigny", "Cugy"],
        zip: "1530",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Corcelles-près-Payerne", km: 3.0 }, { nom: "Fétigny-Ménières", km: 3.1 }, { nom: "Fétigny", km: 3.1 }, { nom: "Cugy", km: 3.2 }],
    },
    {
        slug: "avenches",
        name: "Avenches",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.88513, lng: 7.03416 },
        top_places: ["Belmont-Broye", "Domdidier", "Faoug", "Saint-Aubin"],
        zip: "1580",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Belmont-Broye", km: 2.7 }, { nom: "Domdidier", km: 2.7 }, { nom: "Faoug", km: 3.6 }, { nom: "Saint-Aubin", km: 4.1 }],
    },
    {
        slug: "estavayer-le-lac",
        name: "Estavayer-le-Lac",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.86704, lng: 6.85192 },
        top_places: ["Estavayer", "Vernay", "Sévaz", "Lully"],
        zip: "1470",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Estavayer", km: 1.9 }, { nom: "Vernay", km: 3.0 }, { nom: "Sévaz", km: 3.6 }, { nom: "Lully", km: 3.8 }],
    },
    {
        slug: "saxon",
        name: "Saxon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.13767, lng: 7.18207 },
        top_places: ["Saillon", "Riddes", "Fully", "Leytron"],
        zip: "1907",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Saillon", km: 3.2 }, { nom: "Riddes", km: 4.2 }, { nom: "Fully", km: 5.1 }, { nom: "Leytron", km: 5.3 }],
    },
    {
        slug: "fully",
        name: "Fully",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.16114, lng: 7.12274 },
        top_places: ["Saxon", "Saillon", "Collonges", "Dorénaz"],
        zip: "1926",
        tier: 'HUB',
        heroImage: "/images/generated/solar-hero.webp",
        zones: [{ nom: "Saxon", km: 3.6 }, { nom: "Saillon", km: 4.7 }, { nom: "Collonges", km: 5.6 }, { nom: "Dorénaz", km: 5.7 }],
    },
    {
        slug: "chene-bourg",
        name: "Chêne-Bourg",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19952, lng: 6.19924 },
        top_places: ["Thônex", "Vandœuvres", "Chêne-Bougeries", "Cologny"],
        zip: "1225",
        tier: 'HUB',
        zones: [{ nom: "Thônex", km: 1.3 }, { nom: "Vandœuvres", km: 1.9 }, { nom: "Chêne-Bougeries", km: 2.2 }, { nom: "Cologny", km: 2.3 }],
    },
    {
        slug: "veyrier",
        name: "Veyrier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.17318, lng: 6.16358 },
        top_places: ["Troinex", "Chêne-Bougeries", "Carouge", "Genève"],
        zip: "1255",
        tier: 'HUB',
        zones: [{ nom: "Troinex", km: 1.7 }, { nom: "Chêne-Bougeries", km: 1.9 }, { nom: "Carouge", km: 2.0 }, { nom: "Genève", km: 3.2 }],
    },
    {
        slug: "plan-les-ouates",
        name: "Plan-les-Ouates",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.16372, lng: 6.11979 },
        top_places: ["Troinex", "Perly-Certoux", "Carouge", "Onex"],
        zip: "1228",
        tier: 'HUB',
        zones: [{ nom: "Troinex", km: 2.1 }, { nom: "Perly-Certoux", km: 2.3 }, { nom: "Carouge", km: 2.5 }, { nom: "Onex", km: 2.7 }],
    },
    {
        slug: "bernex",
        name: "Bernex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.18021, lng: 6.06999 },
        top_places: ["Confignon", "Onex", "Aire-la-Ville", "Perly-Certoux"],
        zip: "1233",
        tier: 'HUB',
        zones: [{ nom: "Confignon", km: 1.1 }, { nom: "Onex", km: 2.3 }, { nom: "Aire-la-Ville", km: 2.4 }, { nom: "Perly-Certoux", km: 3.1 }],
    },
    {
        slug: "satigny",
        name: "Satigny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.21531, lng: 6.03351 },
        top_places: ["Russin", "Aire-la-Ville", "Dardagny", "Meyrin"],
        zip: "1242",
        tier: 'HUB',
        zones: [{ nom: "Russin", km: 2.8 }, { nom: "Aire-la-Ville", km: 2.9 }, { nom: "Dardagny", km: 3.7 }, { nom: "Meyrin", km: 4.0 }],
    },
    {
        slug: "laconnex",
        name: "Laconnex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.1592, lng: 6.03336 },
        top_places: ["Soral", "Cartigny", "Avully", "Bernex"],
        zip: "1287",
        tier: 'HUB',
        zones: [{ nom: "Soral", km: 1.9 }, { nom: "Cartigny", km: 1.9 }, { nom: "Avully", km: 2.8 }, { nom: "Bernex", km: 3.4 }],
    },
    {
        slug: "soral",
        name: "Soral",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.14695, lng: 6.04119 },
        top_places: ["Laconnex", "Cartigny", "Avully", "Perly-Certoux"],
        zip: "1286",
        tier: 'HUB',
        zones: [{ nom: "Laconnex", km: 1.4 }, { nom: "Cartigny", km: 3.4 }, { nom: "Avully", km: 4.0 }, { nom: "Perly-Certoux", km: 4.0 }],
    },
    {
        slug: "avusy",
        name: "Avusy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.15195, lng: 6.00578 },
        top_places: ["Avully", "Chancy", "Laconnex", "Cartigny"],
        zip: "1285",
        tier: 'HUB',
        zones: [{ nom: "Avully", km: 1.8 }, { nom: "Chancy", km: 2.1 }, { nom: "Laconnex", km: 2.3 }, { nom: "Cartigny", km: 2.7 }],
    },
    {
        slug: "chancy",
        name: "Chancy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.14639, lng: 5.97453 },
        top_places: ["Avusy", "Avully", "Cartigny", "Laconnex"],
        zip: "1284",
        tier: 'HUB',
        zones: [{ nom: "Avusy", km: 0.8 }, { nom: "Avully", km: 3.0 }, { nom: "Cartigny", km: 4.7 }, { nom: "Laconnex", km: 4.8 }],
    },
    {
        slug: "avully",
        name: "Avully",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.16734, lng: 5.99962 },
        top_places: ["Cartigny", "Avusy", "Chancy", "Laconnex"],
        zip: "1237",
        tier: 'HUB',
        zones: [{ nom: "Cartigny", km: 1.8 }, { nom: "Avusy", km: 2.3 }, { nom: "Chancy", km: 2.7 }, { nom: "Laconnex", km: 2.8 }],
    },
    {
        slug: "puplinge",
        name: "Puplinge",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.21015, lng: 6.22954 },
        top_places: ["Thônex", "Choulex", "Presinge", "Vandœuvres"],
        zip: "1241",
        tier: 'HUB',
        zones: [{ nom: "Thônex", km: 1.5 }, { nom: "Choulex", km: 1.8 }, { nom: "Presinge", km: 2.2 }, { nom: "Vandœuvres", km: 2.4 }],
    },
    {
        slug: "corsier",
        name: "Corsier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.4938, lng: 6.87153 },
        top_places: ["Jongny", "Attalens", "Remaufens", "Bossonnens"],
        zip: "1246",
        tier: 'HUB',
        zones: [{ nom: "Jongny", km: 2.0 }, { nom: "Attalens", km: 2.5 }, { nom: "Remaufens", km: 2.6 }, { nom: "Bossonnens", km: 3.0 }],
    },
    {
        slug: "anieres",
        name: "Anières",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.28034, lng: 6.21693 },
        top_places: ["Corsier", "Hermance", "Tannay", "Collonge-Bellerive"],
        zip: "1247",
        tier: 'HUB',
        zones: [{ nom: "Corsier", km: 2.2 }, { nom: "Hermance", km: 2.6 }, { nom: "Tannay", km: 3.4 }, { nom: "Collonge-Bellerive", km: 3.6 }],
    },
    {
        slug: "collonge-bellerive",
        name: "Collonge-Bellerive",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.25288, lng: 6.20264 },
        top_places: ["Anières", "Corsier", "Meinier", "Choulex"],
        zip: "1245",
        tier: 'HUB',
        zones: [{ nom: "Anières", km: 1.9 }, { nom: "Corsier", km: 2.2 }, { nom: "Meinier", km: 2.7 }, { nom: "Choulex", km: 3.4 }],
    },
    {
        slug: "cologny",
        name: "Cologny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.22124, lng: 6.17681 },
        top_places: ["Vandœuvres", "Chêne-Bourg", "Genève", "Pregny-Chambésy"],
        zip: "1223",
        tier: 'HUB',
        zones: [{ nom: "Vandœuvres", km: 1.9 }, { nom: "Chêne-Bourg", km: 3.1 }, { nom: "Genève", km: 3.1 }, { nom: "Pregny-Chambésy", km: 3.5 }],
    },
    {
        slug: "vanduvres",
        name: "Vandœuvres",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.22005, lng: 6.20349 },
        top_places: ["Cologny", "Choulex", "Puplinge", "Thônex"],
        zip: "1253",
        tier: 'HUB',
        zones: [{ nom: "Cologny", km: 1.6 }, { nom: "Choulex", km: 1.7 }, { nom: "Puplinge", km: 2.4 }, { nom: "Thônex", km: 2.4 }],
    },
    {
        slug: "choulex",
        name: "Choulex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.22443, lng: 6.23037 },
        top_places: ["Puplinge", "Presinge", "Meinier", "Vandœuvres"],
        zip: "1244",
        tier: 'HUB',
        zones: [{ nom: "Puplinge", km: 1.5 }, { nom: "Presinge", km: 2.0 }, { nom: "Meinier", km: 2.1 }, { nom: "Vandœuvres", km: 2.5 }],
    },
    {
        slug: "meinier",
        name: "Meinier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.24154, lng: 6.23514 },
        top_places: ["Gy", "Choulex", "Corsier", "Collonge-Bellerive"],
        zip: "1252",
        tier: 'HUB',
        zones: [{ nom: "Gy", km: 1.5 }, { nom: "Choulex", km: 1.9 }, { nom: "Corsier", km: 2.3 }, { nom: "Collonge-Bellerive", km: 2.9 }],
    },
    {
        slug: "jussy",
        name: "Jussy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23893, lng: 6.28002 },
        top_places: ["Gy", "Presinge", "Meinier", "Choulex"],
        zip: "1254",
        tier: 'HUB',
        zones: [{ nom: "Gy", km: 2.6 }, { nom: "Presinge", km: 2.9 }, { nom: "Meinier", km: 3.5 }, { nom: "Choulex", km: 4.5 }],
    },
    {
        slug: "presinge",
        name: "Presinge",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.21609, lng: 6.26276 },
        top_places: ["Puplinge", "Jussy", "Choulex", "Meinier"],
        zip: "1243",
        tier: 'HUB',
        zones: [{ nom: "Puplinge", km: 2.4 }, { nom: "Jussy", km: 2.7 }, { nom: "Choulex", km: 3.2 }, { nom: "Meinier", km: 3.7 }],
    },
    {
        slug: "hermance",
        name: "Hermance",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.29852, lng: 6.23119 },
        top_places: ["Tannay", "Anières", "Corsier", "Coppet"],
        zip: "1248",
        tier: 'HUB',
        zones: [{ nom: "Tannay", km: 3.7 }, { nom: "Anières", km: 3.7 }, { nom: "Corsier", km: 4.1 }, { nom: "Coppet", km: 4.1 }],
    },
    {
        slug: "bardonnex",
        name: "Bardonnex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.14961, lng: 6.11816 },
        top_places: ["Plan-les-Ouates", "Perly-Certoux", "Troinex", "Carouge"],
        zip: "1257",
        tier: 'HUB',
        zones: [{ nom: "Plan-les-Ouates", km: 1.9 }, { nom: "Perly-Certoux", km: 2.2 }, { nom: "Troinex", km: 2.7 }, { nom: "Carouge", km: 4.0 }],
    },
    {
        slug: "perly-certoux",
        name: "Perly-Certoux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.1582, lng: 6.08795 },
        top_places: ["Plan-les-Ouates", "Bernex", "Confignon", "Bardonnex"],
        zip: "1258",
        tier: 'HUB',
        zones: [{ nom: "Plan-les-Ouates", km: 2.4 }, { nom: "Bernex", km: 2.7 }, { nom: "Confignon", km: 2.8 }, { nom: "Bardonnex", km: 2.9 }],
    },
    {
        slug: "pregny-chambesy",
        name: "Pregny-Chambésy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23775, lng: 6.15353 },
        top_places: ["Bellevue", "Grand-Saconnex", "Genthod", "Cologny"],
        zip: "1292",
        tier: 'HUB',
        zones: [{ nom: "Bellevue", km: 1.4 }, { nom: "Grand-Saconnex", km: 2.9 }, { nom: "Genthod", km: 3.2 }, { nom: "Cologny", km: 3.3 }],
    },
    {
        slug: "bellevue",
        name: "Bellevue",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.25694, lng: 6.13755 },
        top_places: ["Genthod", "Pregny-Chambésy", "Collex-Bossy", "Grand-Saconnex"],
        zip: "1293",
        tier: 'HUB',
        zones: [{ nom: "Genthod", km: 1.4 }, { nom: "Pregny-Chambésy", km: 1.7 }, { nom: "Collex-Bossy", km: 1.9 }, { nom: "Grand-Saconnex", km: 3.1 }],
    },
    {
        slug: "genthod",
        name: "Genthod",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.26373, lng: 6.16352 },
        top_places: ["Bellevue", "Versoix", "Pregny-Chambésy", "Collonge-Bellerive"],
        zip: "1294",
        tier: 'HUB',
        zones: [{ nom: "Bellevue", km: 1.8 }, { nom: "Versoix", km: 2.2 }, { nom: "Pregny-Chambésy", km: 2.9 }, { nom: "Collonge-Bellerive", km: 3.2 }],
    },
    {
        slug: "collex-bossy",
        name: "Collex-Bossy",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.27914, lng: 6.12076 },
        top_places: ["Genthod", "Versoix", "Bellevue", "Mies"],
        zip: "1239",
        tier: 'HUB',
        zones: [{ nom: "Genthod", km: 2.6 }, { nom: "Versoix", km: 3.6 }, { nom: "Bellevue", km: 3.9 }, { nom: "Mies", km: 4.2 }],
    },
    {
        slug: "troinex",
        name: "Troinex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.15808, lng: 6.15722 },
        top_places: ["Veyrier", "Carouge", "Plan-les-Ouates", "Chêne-Bougeries"],
        zip: "1256",
        tier: 'HUB',
        zones: [{ nom: "Veyrier", km: 2.2 }, { nom: "Carouge", km: 2.9 }, { nom: "Plan-les-Ouates", km: 3.3 }, { nom: "Chêne-Bougeries", km: 3.5 }],
    },
    {
        slug: "confignon",
        name: "Confignon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.17782, lng: 6.08707 },
        top_places: ["Onex", "Bernex", "Perly-Certoux", "Lancy"],
        zip: "1232",
        tier: 'HUB',
        zones: [{ nom: "Onex", km: 1.2 }, { nom: "Bernex", km: 1.4 }, { nom: "Perly-Certoux", km: 2.4 }, { nom: "Lancy", km: 2.6 }],
    },
    {
        slug: "dardagny",
        name: "Dardagny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19899, lng: 5.9834 },
        top_places: ["Russin", "Avully", "Cartigny", "Satigny"],
        zip: "1283",
        tier: 'HUB',
        zones: [{ nom: "Russin", km: 2.4 }, { nom: "Avully", km: 3.7 }, { nom: "Cartigny", km: 4.0 }, { nom: "Satigny", km: 4.4 }],
    },
    {
        slug: "russin",
        name: "Russin",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19349, lng: 6.01622 },
        top_places: ["Dardagny", "Aire-la-Ville", "Cartigny", "Satigny"],
        zip: "1281",
        tier: 'HUB',
        zones: [{ nom: "Dardagny", km: 1.7 }, { nom: "Aire-la-Ville", km: 2.0 }, { nom: "Cartigny", km: 2.2 }, { nom: "Satigny", km: 2.8 }],
    },
    {
        slug: "aire-la-ville",
        name: "Aire-la-Ville",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19072, lng: 6.04536 },
        top_places: ["Bernex", "Russin", "Cartigny", "Satigny"],
        zip: "1288",
        tier: 'HUB',
        zones: [{ nom: "Bernex", km: 2.2 }, { nom: "Russin", km: 2.4 }, { nom: "Cartigny", km: 2.6 }, { nom: "Satigny", km: 2.7 }],
    },
    {
        slug: "cartigny",
        name: "Cartigny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.17502, lng: 6.02991 },
        top_places: ["Laconnex", "Aire-la-Ville", "Russin", "Avully"],
        zip: "1236",
        tier: 'HUB',
        zones: [{ nom: "Laconnex", km: 1.8 }, { nom: "Aire-la-Ville", km: 1.9 }, { nom: "Russin", km: 2.4 }, { nom: "Avully", km: 2.6 }],
    },
    {
        slug: "ecublens",
        name: "Écublens",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.5286, lng: 6.5575 },
        top_places: ["Echandens", "Chavannes-près-Renens", "Saint-Sulpice", "Denges"],
        zip: "1024",
        tier: 'HUB',
        zones: [{ nom: "Echandens", km: 0.8 }, { nom: "Chavannes-près-Renens", km: 1.4 }, { nom: "Saint-Sulpice", km: 1.5 }, { nom: "Denges", km: 1.5 }],
    },
    {
        slug: "crissier",
        name: "Crissier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.56153, lng: 6.57579 },
        top_places: ["Villars-Sainte-Croix", "Romanel-sur-Lausanne", "Mex", "Jouxtens-Mézery"],
        zip: "1023",
        tier: 'HUB',
        zones: [{ nom: "Villars-Sainte-Croix", km: 0.9 }, { nom: "Romanel-sur-Lausanne", km: 1.9 }, { nom: "Mex", km: 2.2 }, { nom: "Jouxtens-Mézery", km: 2.3 }],
    },
    {
        slug: "chavannes-pres-renens",
        name: "Chavannes-près-Renens",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.5293, lng: 6.57296 },
        top_places: ["Ecublens", "Renens", "Saint-Sulpice", "Echandens"],
        zip: "1022",
        tier: 'HUB',
        zones: [{ nom: "Ecublens", km: 1.0 }, { nom: "Renens", km: 1.4 }, { nom: "Saint-Sulpice", km: 1.5 }, { nom: "Echandens", km: 1.8 }],
    },
    {
        slug: "le-mont-sur-lausanne",
        name: "Le Mont-sur-Lausanne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.55898, lng: 6.63969 },
        top_places: ["Épalinges", "Cugy", "Morrens", "Lausanne"],
        zip: "1052",
        tier: 'HUB',
        zones: [{ nom: "Épalinges", km: 2.3 }, { nom: "Cugy", km: 2.5 }, { nom: "Morrens", km: 2.8 }, { nom: "Lausanne", km: 2.9 }],
    },
    {
        slug: "epalinges",
        name: "Epalinges",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.55237, lng: 6.67174 },
        top_places: ["Le Mont-sur-Lausanne", "Belmont-sur-Lausanne", "Lausanne", "Savigny"],
        zip: "1066",
        tier: 'HUB',
        zones: [{ nom: "Le Mont-sur-Lausanne", km: 2.9 }, { nom: "Belmont-sur-Lausanne", km: 3.1 }, { nom: "Lausanne", km: 3.6 }, { nom: "Savigny", km: 3.8 }],
    },
    {
        slug: "savigny",
        name: "Savigny",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.54589, lng: 6.72554 },
        top_places: ["Forel", "Belmont-sur-Lausanne", "Lutry", "Montpreveyres"],
        zip: "1073",
        tier: 'HUB',
        zones: [{ nom: "Forel", km: 3.0 }, { nom: "Belmont-sur-Lausanne", km: 3.6 }, { nom: "Lutry", km: 4.0 }, { nom: "Montpreveyres", km: 4.2 }],
    },
    {
        slug: "lutry",
        name: "Lutry",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.47554, lng: 6.68519 },
        top_places: ["Bourg-en-Lavaux", "Paudex", "Pully", "Belmont-sur-Lausanne"],
        zip: "1095",
        tier: 'HUB',
        zones: [{ nom: "Bourg-en-Lavaux", km: 3.6 }, { nom: "Paudex", km: 3.8 }, { nom: "Pully", km: 4.8 }, { nom: "Belmont-sur-Lausanne", km: 5.7 }],
    },
    {
        slug: "bourg-en-lavaux",
        name: "Bourg-en-Lavaux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.47002, lng: 6.71855 },
        top_places: ["Puidoux", "Rivaz", "Chexbres", "Lutry"],
        zip: "1096",
        tier: 'HUB',
        zones: [{ nom: "Puidoux", km: 4.0 }, { nom: "Rivaz", km: 4.7 }, { nom: "Chexbres", km: 5.0 }, { nom: "Lutry", km: 5.2 }],
    },
    {
        slug: "chexbres",
        name: "Chexbres",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.48408, lng: 6.77864 },
        top_places: ["Rivaz", "Puidoux", "Saint-Saphorin", "Chardonne"],
        zip: "1071",
        tier: 'HUB',
        zones: [{ nom: "Rivaz", km: 0.9 }, { nom: "Puidoux", km: 0.9 }, { nom: "Saint-Saphorin", km: 2.5 }, { nom: "Chardonne", km: 3.3 }],
    },
    {
        slug: "puidoux",
        name: "Puidoux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.49338, lng: 6.79321 },
        top_places: ["Chexbres", "Rivaz", "Chardonne", "Saint-Saphorin"],
        zip: "1070",
        tier: 'HUB',
        zones: [{ nom: "Chexbres", km: 1.4 }, { nom: "Rivaz", km: 2.2 }, { nom: "Chardonne", km: 2.2 }, { nom: "Saint-Saphorin", km: 3.0 }],
    },
    {
        slug: "la-tour-de-peilz",
        name: "La Tour-de-Peilz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.43476, lng: 6.85482 },
        top_places: ["Corsier-sur-Vevey", "Vevey", "Corseaux", "Montreux"],
        zip: "1814",
        tier: 'HUB',
        zones: [{ nom: "Corsier-sur-Vevey", km: 3.6 }, { nom: "Vevey", km: 3.6 }, { nom: "Corseaux", km: 3.9 }, { nom: "Montreux", km: 4.4 }],
    },
    {
        slug: "villeneuve",
        name: "Villeneuve",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.40636, lng: 6.95311 },
        top_places: ["Veytaux", "Montreux", "Corbeyrier", "Noville"],
        zip: "1844",
        tier: 'HUB',
        zones: [{ nom: "Veytaux", km: 2.6 }, { nom: "Montreux", km: 4.5 }, { nom: "Corbeyrier", km: 4.6 }, { nom: "Noville", km: 4.8 }],
    },
    {
        slug: "aigle",
        name: "Aigle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.31642, lng: 6.96974 },
        top_places: ["Yvorne", "Ollon", "Leysin", "Vionnaz"],
        zip: "1860",
        tier: 'HUB',
        zones: [{ nom: "Yvorne", km: 2.4 }, { nom: "Ollon", km: 2.8 }, { nom: "Leysin", km: 3.0 }, { nom: "Vionnaz", km: 5.4 }],
    },
    {
        slug: "ollon",
        name: "Ollon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.30191, lng: 7.03173 },
        top_places: ["Leysin", "Gryon", "Aigle", "Bex"],
        zip: "1867",
        tier: 'HUB',
        zones: [{ nom: "Leysin", km: 4.3 }, { nom: "Gryon", km: 5.2 }, { nom: "Aigle", km: 5.4 }, { nom: "Bex", km: 5.9 }],
    },
    {
        slug: "bex",
        name: "Bex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.25166, lng: 7.07126 },
        top_places: ["Gryon", "Saint-Maurice", "Lavey-Morcles", "Massongex"],
        zip: "1880",
        tier: 'HUB',
        zones: [{ nom: "Gryon", km: 4.8 }, { nom: "Saint-Maurice", km: 6.3 }, { nom: "Lavey-Morcles", km: 6.4 }, { nom: "Massongex", km: 6.8 }],
    },
    {
        slug: "grandson",
        name: "Grandson",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.81154, lng: 6.6566 },
        top_places: ["Champagne", "Giez", "Bonvillars", "Onnens"],
        zip: "1422",
        tier: 'HUB',
        zones: [{ nom: "Champagne", km: 2.7 }, { nom: "Giez", km: 3.1 }, { nom: "Bonvillars", km: 3.1 }, { nom: "Onnens", km: 3.2 }],
    },
    {
        slug: "orbe",
        name: "Orbe",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.72268, lng: 6.54327 },
        top_places: ["Montcherand", "Chavornay", "Valeyres-sous-Rances", "Arnex-sur-Orbe"],
        zip: "1350",
        tier: 'HUB',
        zones: [{ nom: "Montcherand", km: 2.3 }, { nom: "Chavornay", km: 2.7 }, { nom: "Valeyres-sous-Rances", km: 3.1 }, { nom: "Arnex-sur-Orbe", km: 3.2 }],
    },
    {
        slug: "vallorbe",
        name: "Vallorbe",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.70784, lng: 6.3741 },
        top_places: ["Vaulion", "Ballaigues", "Premier", "Juriens"],
        zip: "1337",
        tier: 'HUB',
        zones: [{ nom: "Vaulion", km: 2.8 }, { nom: "Ballaigues", km: 4.3 }, { nom: "Premier", km: 5.5 }, { nom: "Juriens", km: 6.4 }],
    },
    {
        slug: "saint-prex",
        name: "Saint-Prex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.46226, lng: 6.47472 },
        top_places: ["Lully", "Tolochenaz", "Buchillon", "Lussy-sur-Morges"],
        zip: "1162",
        tier: 'HUB',
        zones: [{ nom: "Lully", km: 4.2 }, { nom: "Tolochenaz", km: 4.2 }, { nom: "Buchillon", km: 4.5 }, { nom: "Lussy-sur-Morges", km: 4.6 }],
    },
    {
        slug: "aubonne",
        name: "Aubonne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.49685, lng: 6.3635 },
        top_places: ["Féchy", "Bougy-Villars", "Saint-Livres", "Saubraz"],
        zip: "1170",
        tier: 'HUB',
        zones: [{ nom: "Féchy", km: 1.5 }, { nom: "Bougy-Villars", km: 1.8 }, { nom: "Saint-Livres", km: 2.2 }, { nom: "Saubraz", km: 3.2 }],
    },
    {
        slug: "prangins",
        name: "Prangins",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.39229, lng: 6.25957 },
        top_places: ["Nyon", "Gland", "Coinsins", "Duillier"],
        zip: "1197",
        tier: 'HUB',
        zones: [{ nom: "Nyon", km: 2.0 }, { nom: "Gland", km: 2.8 }, { nom: "Coinsins", km: 3.4 }, { nom: "Duillier", km: 3.4 }],
    },
    {
        slug: "coppet",
        name: "Coppet",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.31627, lng: 6.20253 },
        top_places: ["Commugny", "Tannay", "Founex", "Mies"],
        zip: "1296",
        tier: 'HUB',
        zones: [{ nom: "Commugny", km: 1.5 }, { nom: "Tannay", km: 2.3 }, { nom: "Founex", km: 2.6 }, { nom: "Mies", km: 3.3 }],
    },
    {
        slug: "moudon",
        name: "Moudon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.67041, lng: 6.78568 },
        top_places: ["Rossenges", "Syens", "Chavannes-sur-Moudon", "Bussy-sur-Moudon"],
        zip: "1510",
        tier: 'HUB',
        zones: [{ nom: "Rossenges", km: 2.3 }, { nom: "Syens", km: 2.3 }, { nom: "Chavannes-sur-Moudon", km: 2.5 }, { nom: "Bussy-sur-Moudon", km: 2.8 }],
    },
    {
        slug: "echallens",
        name: "Echallens",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.63776, lng: 6.63501 },
        top_places: ["Villars-le-Terroir", "Assens", "Saint-Barthélemy", "Montilliez"],
        zip: "1040",
        tier: 'HUB',
        zones: [{ nom: "Villars-le-Terroir", km: 1.4 }, { nom: "Assens", km: 2.3 }, { nom: "Saint-Barthélemy", km: 2.7 }, { nom: "Montilliez", km: 2.8 }],
    },
    {
        slug: "cossonay",
        name: "Cossonay",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.6127, lng: 6.5014 },
        top_places: ["Senarclens", "Penthalaz", "La Chaux (Cossonay)", "Dizy"],
        zip: "1304",
        tier: 'HUB',
        zones: [{ nom: "Senarclens", km: 2.0 }, { nom: "Penthalaz", km: 2.1 }, { nom: "La Chaux (Cossonay)", km: 2.2 }, { nom: "Dizy", km: 2.3 }],
    },
    {
        slug: "la-sarraz",
        name: "La Sarraz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.65501, lng: 6.50806 },
        top_places: ["Pompaples", "Chevilly", "Eclépens", "Orny"],
        zip: "1315",
        tier: 'HUB',
        zones: [{ nom: "Pompaples", km: 1.5 }, { nom: "Chevilly", km: 2.0 }, { nom: "Eclépens", km: 2.0 }, { nom: "Orny", km: 2.1 }],
    },
    {
        slug: "lisle",
        name: "L'Isle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.62106, lng: 6.40625 },
        top_places: ["Mauraz", "Cuarnens", "Mont-la-Ville", "Montricher"],
        zip: "1148",
        tier: 'HUB',
        zones: [{ nom: "Mauraz", km: 2.5 }, { nom: "Cuarnens", km: 2.5 }, { nom: "Mont-la-Ville", km: 2.8 }, { nom: "Montricher", km: 3.8 }],
    },
    {
        slug: "le-sentier",
        name: "Le Sentier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.63482, lng: 6.6021 },
        top_places: ["Saint-Barthélemy", "Bettens", "Goumoëns", "Oulens-sous-Échallens"],
        zip: "1347",
        tier: 'HUB',
        zones: [{ nom: "Saint-Barthélemy", km: 0.2 }, { nom: "Bettens", km: 1.4 }, { nom: "Goumoëns", km: 1.7 }, { nom: "Oulens-sous-Échallens", km: 2.2 }],
    },
    {
        slug: "sainte-croix",
        name: "Sainte-Croix",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.82458, lng: 6.48658 },
        top_places: ["La Côte-aux-Fées", "Vuitebœuf", "Baulmes", "Bullet"],
        zip: "1450",
        tier: 'HUB',
        zones: [{ nom: "La Côte-aux-Fées", km: 4.7 }, { nom: "Vuitebœuf", km: 5.1 }, { nom: "Baulmes", km: 5.1 }, { nom: "Bullet", km: 5.7 }],
    },
    {
        slug: "chateau-dx",
        name: "Château-d'Œx",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.45373, lng: 7.13922 },
        top_places: ["Château-d’Oex", "Rossinière", "Rougemont", "Haut-Intyamon"],
        zip: "1660",
        tier: 'HUB',
        zones: [{ nom: "Château-d’Oex", km: 2.2 }, { nom: "Rossinière", km: 4.5 }, { nom: "Rougemont", km: 7.5 }, { nom: "Haut-Intyamon", km: 9.5 }],
    },
    {
        slug: "chamoson",
        name: "Chamoson",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.21133, lng: 7.1965 },
        top_places: ["Leytron", "Ardon", "Saillon", "Riddes"],
        zip: "1955",
        tier: 'HUB',
        zones: [{ nom: "Leytron", km: 3.1 }, { nom: "Ardon", km: 4.3 }, { nom: "Saillon", km: 5.1 }, { nom: "Riddes", km: 5.2 }],
    },
    {
        slug: "ardon",
        name: "Ardon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.22732, lng: 7.23726 },
        top_places: ["Vétroz", "Chamoson", "Conthey", "Conthey"],
        zip: "1957",
        tier: 'HUB',
        zones: [{ nom: "Vétroz", km: 2.6 }, { nom: "Chamoson", km: 3.4 }, { nom: "Conthey", km: 5.0 }, { nom: "Conthey", km: 5.2 }],
    },
    {
        slug: "vetroz",
        name: "Vétroz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23438, lng: 7.25536 },
        top_places: ["Ardon", "Conthey", "Conthey", "Chamoson"],
        zip: "1963",
        tier: 'HUB',
        zones: [{ nom: "Ardon", km: 3.8 }, { nom: "Conthey", km: 4.0 }, { nom: "Conthey", km: 4.2 }, { nom: "Chamoson", km: 4.8 }],
    },
    {
        slug: "nendaz",
        name: "Nendaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.13592, lng: 7.32051 },
        top_places: ["Isérables", "Veysonnaz", "Hérémence", "Riddes"],
        zip: "1997",
        tier: 'HUB',
        zones: [{ nom: "Isérables", km: 6.7 }, { nom: "Veysonnaz", km: 6.9 }, { nom: "Hérémence", km: 8.1 }, { nom: "Riddes", km: 8.7 }],
    },
    {
        slug: "veysonnaz",
        name: "Veysonnaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19828, lng: 7.33773 },
        top_places: ["Nendaz", "Conthey", "Sion", "Hérémence"],
        zip: "1993",
        tier: 'HUB',
        zones: [{ nom: "Nendaz", km: 3.3 }, { nom: "Conthey", km: 3.6 }, { nom: "Sion", km: 4.2 }, { nom: "Hérémence", km: 5.1 }],
    },
    {
        slug: "saviese",
        name: "Savièse",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.30404, lng: 7.33326 },
        top_places: ["Ayent", "Grimisuat", "Arbaz", "Ayent"],
        zip: "1965",
        tier: 'HUB',
        zones: [{ nom: "Ayent", km: 5.6 }, { nom: "Grimisuat", km: 5.7 }, { nom: "Arbaz", km: 5.7 }, { nom: "Ayent", km: 6.5 }],
    },
    {
        slug: "grimisuat",
        name: "Grimisuat",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.25552, lng: 7.38113 },
        top_places: ["Arbaz", "Sion", "Ayent", "Saint-Léonard"],
        zip: "1971",
        tier: 'HUB',
        zones: [{ nom: "Arbaz", km: 1.3 }, { nom: "Sion", km: 3.0 }, { nom: "Ayent", km: 3.4 }, { nom: "Saint-Léonard", km: 3.5 }],
    },
    {
        slug: "ayent",
        name: "Ayent",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.31902, lng: 7.4166 },
        top_places: ["Icogne", "Lens", "Crans-Montana", "Grimisuat"],
        zip: "1966",
        tier: 'HUB',
        zones: [{ nom: "Icogne", km: 4.2 }, { nom: "Lens", km: 4.9 }, { nom: "Crans-Montana", km: 5.1 }, { nom: "Grimisuat", km: 6.4 }],
    },
    {
        slug: "chalais",
        name: "Chalais",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.24604, lng: 7.53379 },
        top_places: ["Chippis", "Sierre", "Noble-Contrée", "Anniviers"],
        zip: "3966",
        tier: 'HUB',
        zones: [{ nom: "Chippis", km: 4.1 }, { nom: "Sierre", km: 5.1 }, { nom: "Noble-Contrée", km: 6.0 }, { nom: "Anniviers", km: 6.4 }],
    },
    {
        slug: "venthone",
        name: "Venthône",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.3053, lng: 7.532 },
        top_places: ["Noble-Contrée", "Sierre", "Chippis", "Salquenen"],
        zip: "3973",
        tier: 'HUB',
        zones: [{ nom: "Noble-Contrée", km: 0.6 }, { nom: "Sierre", km: 1.5 }, { nom: "Chippis", km: 2.4 }, { nom: "Salquenen", km: 2.7 }],
    },
    {
        slug: "montana",
        name: "Montana",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.69423, lng: 6.76106 },
        top_places: ["Boulens", "Montanaire", "Villars-le-Comte", "Moudon"],
        zip: "3963",
        tier: 'HUB',
        zones: [{ nom: "Boulens", km: 3.6 }, { nom: "Montanaire", km: 3.7 }, { nom: "Villars-le-Comte", km: 3.9 }, { nom: "Moudon", km: 4.0 }],
    },
    {
        slug: "randogne",
        name: "Randogne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.0953, lng: 7.7858 },
        top_places: ["Randa", "Täsch", "Täsch", "Grächen"],
        zip: "3975",
        tier: 'HUB',
        zones: [{ nom: "Randa", km: 0.6 }, { nom: "Täsch", km: 3.5 }, { nom: "Täsch", km: 5.0 }, { nom: "Grächen", km: 8.3 }],
    },
    {
        slug: "chermignon",
        name: "Chermignon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.61842, lng: 7.19361 },
        top_places: ["Val-de-Charmey", "Crésuz", "Châtel-sur-Montsalvens", "Jaun"],
        zip: "3971",
        tier: 'HUB',
        zones: [{ nom: "Val-de-Charmey", km: 2.2 }, { nom: "Crésuz", km: 4.6 }, { nom: "Châtel-sur-Montsalvens", km: 4.6 }, { nom: "Jaun", km: 5.6 }],
    },
    {
        slug: "lens",
        name: "Lens",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.30274, lng: 7.45816 },
        top_places: ["Crans-Montana", "Icogne", "Ayent", "Ayent"],
        zip: "1978",
        tier: 'HUB',
        zones: [{ nom: "Crans-Montana", km: 2.1 }, { nom: "Icogne", km: 2.9 }, { nom: "Ayent", km: 4.6 }, { nom: "Ayent", km: 5.0 }],
    },
    {
        slug: "grone",
        name: "Grône",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.2309, lng: 7.48643 },
        top_places: ["Chalais", "Mont-Noble", "Saint-Léonard", "Lens"],
        zip: "3979",
        tier: 'HUB',
        zones: [{ nom: "Chalais", km: 4.1 }, { nom: "Mont-Noble", km: 4.4 }, { nom: "Saint-Léonard", km: 5.4 }, { nom: "Lens", km: 6.3 }],
    },
    {
        slug: "saint-leonard",
        name: "Saint-Léonard",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.2562, lng: 7.42866 },
        top_places: ["Grône", "Mont-Noble", "Icogne", "Lens"],
        zip: "1958",
        tier: 'HUB',
        zones: [{ nom: "Grône", km: 1.8 }, { nom: "Mont-Noble", km: 2.9 }, { nom: "Icogne", km: 3.0 }, { nom: "Lens", km: 3.1 }],
    },
    {
        slug: "salgesch",
        name: "Salgesch",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.3087, lng: 7.57195 },
        top_places: ["Salquenen", "Varonne", "Noble-Contrée", "Sierre"],
        zip: "3970",
        tier: 'HUB',
        zones: [{ nom: "Salquenen", km: 1.0 }, { nom: "Varonne", km: 2.3 }, { nom: "Noble-Contrée", km: 3.1 }, { nom: "Sierre", km: 3.6 }],
    },
    {
        slug: "varen",
        name: "Varen",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.33932, lng: 7.5972 },
        top_places: ["Inden", "Varonne", "Albinen", "Loèche"],
        zip: "3953",
        tier: 'HUB',
        zones: [{ nom: "Inden", km: 1.6 }, { nom: "Varonne", km: 2.5 }, { nom: "Albinen", km: 2.9 }, { nom: "Loèche", km: 3.7 }],
    },
    {
        slug: "bovernier",
        name: "Bovernier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.05733, lng: 7.08405 },
        top_places: ["Martigny-Combe", "Martigny", "Sembrancher", "Orsières"],
        zip: "1932",
        tier: 'HUB',
        zones: [{ nom: "Martigny-Combe", km: 3.9 }, { nom: "Martigny", km: 4.8 }, { nom: "Sembrancher", km: 5.7 }, { nom: "Orsières", km: 5.7 }],
    },
    {
        slug: "sembrancher",
        name: "Sembrancher",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.06998, lng: 7.14829 },
        top_places: ["Orsières", "Val de Bagnes", "Bovernier", "Martigny"],
        zip: "1933",
        tier: 'HUB',
        zones: [{ nom: "Orsières", km: 4.1 }, { nom: "Val de Bagnes", km: 5.0 }, { nom: "Bovernier", km: 5.2 }, { nom: "Martigny", km: 6.7 }],
    },
    {
        slug: "bourg-saint-pierre",
        name: "Bourg-Saint-Pierre",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 45.91652, lng: 7.214 },
        top_places: ["Liddes", "Orsières", "Orsières", "Val de Bagnes"],
        zip: "1946",
        tier: 'HUB',
        zones: [{ nom: "Liddes", km: 7.8 }, { nom: "Orsières", km: 10.7 }, { nom: "Orsières", km: 13.9 }, { nom: "Val de Bagnes", km: 18.2 }],
    },
    {
        slug: "liddes",
        name: "Liddes",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 45.96803, lng: 7.24645 },
        top_places: ["Bourg-Saint-Pierre", "Orsières", "Orsières", "Val de Bagnes"],
        zip: "1945",
        tier: 'HUB',
        zones: [{ nom: "Bourg-Saint-Pierre", km: 4.1 }, { nom: "Orsières", km: 10.4 }, { nom: "Orsières", km: 11.2 }, { nom: "Val de Bagnes", km: 12.8 }],
    },
    {
        slug: "volleges",
        name: "Vollèges",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.58341, lng: 8.60194 },
        top_places: ["Flaach", "Berg am Irchel", "Volken", "Rüdlingen"],
        zip: "1941",
        tier: 'HUB',
        zones: [{ nom: "Flaach", km: 1.0 }, { nom: "Berg am Irchel", km: 1.9 }, { nom: "Volken", km: 2.0 }, { nom: "Rüdlingen", km: 3.3 }],
    },
    {
        slug: "orsieres",
        name: "Orsières",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 45.95924, lng: 7.08133 },
        top_places: ["Liddes", "Bourg-Saint-Pierre", "Trient", "Bovernier"],
        zip: "1937",
        tier: 'HUB',
        zones: [{ nom: "Liddes", km: 8.3 }, { nom: "Bourg-Saint-Pierre", km: 9.2 }, { nom: "Trient", km: 11.9 }, { nom: "Bovernier", km: 13.8 }],
    },
    {
        slug: "massongex",
        name: "Massongex",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.23232, lng: 6.98762 },
        top_places: ["Vérossaz", "Saint-Maurice", "Bex", "Monthey"],
        zip: "1869",
        tier: 'HUB',
        zones: [{ nom: "Vérossaz", km: 1.8 }, { nom: "Saint-Maurice", km: 2.0 }, { nom: "Bex", km: 3.0 }, { nom: "Monthey", km: 3.5 }],
    },
    {
        slug: "verossaz",
        name: "Vérossaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.19864, lng: 6.96397 },
        top_places: ["Saint-Maurice", "Val-d'Illiez", "Evionnaz", "Troistorrents"],
        zip: "1891",
        tier: 'HUB',
        zones: [{ nom: "Saint-Maurice", km: 3.9 }, { nom: "Val-d'Illiez", km: 4.9 }, { nom: "Evionnaz", km: 5.0 }, { nom: "Troistorrents", km: 5.3 }],
    },
    {
        slug: "evionnaz",
        name: "Evionnaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.15157, lng: 6.94442 },
        top_places: ["Champéry", "Val-d'Illiez", "Salvan", "Collonges"],
        zip: "1902",
        tier: 'HUB',
        zones: [{ nom: "Champéry", km: 6.2 }, { nom: "Val-d'Illiez", km: 6.4 }, { nom: "Salvan", km: 6.8 }, { nom: "Collonges", km: 7.1 }],
    },
    {
        slug: "salvan",
        name: "Salvan",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.11181, lng: 6.96015 },
        top_places: ["Finhaut", "Vernayaz", "Trient", "Martigny-Combe"],
        zip: "1922",
        tier: 'HUB',
        zones: [{ nom: "Finhaut", km: 3.4 }, { nom: "Vernayaz", km: 6.1 }, { nom: "Trient", km: 7.5 }, { nom: "Martigny-Combe", km: 7.6 }],
    },
    {
        slug: "finhaut",
        name: "Finhaut",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.07196, lng: 6.93527 },
        top_places: ["Trient", "Salvan", "Martigny-Combe", "Vernayaz"],
        zip: "1925",
        tier: 'HUB',
        zones: [{ nom: "Trient", km: 5.6 }, { nom: "Salvan", km: 8.0 }, { nom: "Martigny-Combe", km: 8.9 }, { nom: "Vernayaz", km: 10.2 }],
    },
    {
        slug: "trient",
        name: "Trient",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.03212, lng: 6.9966 },
        top_places: ["Finhaut", "Martigny-Combe", "Bovernier", "Salvan"],
        zip: "1929",
        tier: 'HUB',
        zones: [{ nom: "Finhaut", km: 5.9 }, { nom: "Martigny-Combe", km: 7.0 }, { nom: "Bovernier", km: 8.8 }, { nom: "Salvan", km: 9.5 }],
    },
    {
        slug: "collombey-muraz",
        name: "Collombey-Muraz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.2869, lng: 6.92468 },
        top_places: ["Vionnaz", "Monthey", "Aigle", "Ollon"],
        zip: "1868",
        tier: 'HUB',
        zones: [{ nom: "Vionnaz", km: 3.8 }, { nom: "Monthey", km: 4.5 }, { nom: "Aigle", km: 4.6 }, { nom: "Ollon", km: 5.4 }],
    },
    {
        slug: "troistorrents",
        name: "Troistorrents",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.229, lng: 6.88534 },
        top_places: ["Val-d'Illiez", "Monthey", "Champéry", "Collombey-Muraz"],
        zip: "1872",
        tier: 'HUB',
        zones: [{ nom: "Val-d'Illiez", km: 3.4 }, { nom: "Monthey", km: 5.5 }, { nom: "Champéry", km: 6.1 }, { nom: "Collombey-Muraz", km: 6.5 }],
    },
    {
        slug: "champery",
        name: "Champéry",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.1596, lng: 6.84911 },
        top_places: ["Val-d'Illiez", "Troistorrents", "Vérossaz", "Monthey"],
        zip: "1874",
        tier: 'HUB',
        zones: [{ nom: "Val-d'Illiez", km: 6.0 }, { nom: "Troistorrents", km: 9.7 }, { nom: "Vérossaz", km: 12.1 }, { nom: "Monthey", km: 12.7 }],
    },
    {
        slug: "val-dilliez",
        name: "Val-d'Illiez",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.18711, lng: 6.91629 },
        top_places: ["Champéry", "Troistorrents", "Vérossaz", "Monthey"],
        zip: "1873",
        tier: 'HUB',
        zones: [{ nom: "Champéry", km: 3.7 }, { nom: "Troistorrents", km: 5.1 }, { nom: "Vérossaz", km: 6.1 }, { nom: "Monthey", km: 7.5 }],
    },
    {
        slug: "vionnaz",
        name: "Vionnaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.30674, lng: 6.87442 },
        top_places: ["Vouvry", "Chessel", "Roche", "Yvorne"],
        zip: "1895",
        tier: 'HUB',
        zones: [{ nom: "Vouvry", km: 3.0 }, { nom: "Chessel", km: 5.0 }, { nom: "Roche", km: 5.8 }, { nom: "Yvorne", km: 6.5 }],
    },
    {
        slug: "vouvry",
        name: "Vouvry",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.33812, lng: 6.85177 },
        top_places: ["Port-Valais", "Port-Valais", "Chessel", "Vionnaz"],
        zip: "1896",
        tier: 'HUB',
        zones: [{ nom: "Port-Valais", km: 3.3 }, { nom: "Port-Valais", km: 3.4 }, { nom: "Chessel", km: 3.6 }, { nom: "Vionnaz", km: 4.4 }],
    },
    {
        slug: "port-valais",
        name: "Port-Valais",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.3738, lng: 6.86237 },
        top_places: ["Noville", "Chessel", "Rennaz", "Saint-Gingolph"],
        zip: "1897",
        tier: 'HUB',
        zones: [{ nom: "Noville", km: 3.1 }, { nom: "Chessel", km: 3.7 }, { nom: "Rennaz", km: 4.2 }, { nom: "Saint-Gingolph", km: 4.7 }],
    },
    {
        slug: "boudry",
        name: "Boudry",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.95493, lng: 6.81892 },
        top_places: ["Cortaillod", "Rochefort", "Milvignes", "Brot-Plamboz"],
        zip: "2017",
        tier: 'HUB',
        zones: [{ nom: "Cortaillod", km: 2.5 }, { nom: "Rochefort", km: 3.2 }, { nom: "Milvignes", km: 3.9 }, { nom: "Brot-Plamboz", km: 6.0 }],
    },
    {
        slug: "colombier",
        name: "Colombier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.2869, lng: 6.92468 },
        top_places: ["Collombey-Muraz", "Vionnaz", "Monthey", "Aigle"],
        zip: "2013",
        tier: 'HUB',
        zones: [{ nom: "Collombey-Muraz", km: 3.0 }, { nom: "Vionnaz", km: 3.8 }, { nom: "Monthey", km: 4.5 }, { nom: "Aigle", km: 4.6 }],
    },
    {
        slug: "cortaillod",
        name: "Cortaillod",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.94265, lng: 6.84619 },
        top_places: ["Boudry", "Milvignes", "Rochefort", "Vernay"],
        zip: "2016",
        tier: 'HUB',
        zones: [{ nom: "Boudry", km: 1.3 }, { nom: "Milvignes", km: 3.1 }, { nom: "Rochefort", km: 5.0 }, { nom: "Vernay", km: 7.2 }],
    },
    {
        slug: "bevaix",
        name: "Bevaix",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.67967, lng: 6.56812 },
        top_places: ["Bavois", "Penthéréaz", "Chavornay", "Orny"],
        zip: "2022",
        tier: 'HUB',
        zones: [{ nom: "Bavois", km: 0.4 }, { nom: "Penthéréaz", km: 2.5 }, { nom: "Chavornay", km: 3.0 }, { nom: "Orny", km: 3.4 }],
    },
    {
        slug: "saint-aubin-sauges",
        name: "Saint-Aubin-Sauges",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.89183, lng: 6.9824 },
        top_places: ["Saint-Aubin", "Missy", "Vallon", "Delley-Portalban"],
        zip: "2024",
        tier: 'HUB',
        zones: [{ nom: "Saint-Aubin", km: 0.2 }, { nom: "Missy", km: 1.9 }, { nom: "Vallon", km: 2.3 }, { nom: "Delley-Portalban", km: 2.6 }],
    },
    {
        slug: "auvernier",
        name: "Auvernier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.34302, lng: 6.92601 },
        top_places: ["Roche", "Yvorne", "Chessel", "Rennaz"],
        zip: "2012",
        tier: 'HUB',
        zones: [{ nom: "Roche", km: 1.1 }, { nom: "Yvorne", km: 2.1 }, { nom: "Chessel", km: 2.5 }, { nom: "Rennaz", km: 2.7 }],
    },
    {
        slug: "peseux",
        name: "Peseux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.56262, lng: 7.09656 },
        top_places: ["Bas-Intyamon", "Gruyères", "Grandvillard", "Broc"],
        zip: "2034",
        tier: 'HUB',
        zones: [{ nom: "Bas-Intyamon", km: 1.1 }, { nom: "Gruyères", km: 2.6 }, { nom: "Grandvillard", km: 3.4 }, { nom: "Broc", km: 4.2 }],
    },
    {
        slug: "valangin",
        name: "Valangin",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.88329, lng: 6.95307 },
        top_places: ["Vallon", "Gletterens", "Missy", "Saint-Aubin"],
        zip: "2042",
        tier: 'HUB',
        zones: [{ nom: "Vallon", km: 0.2 }, { nom: "Gletterens", km: 1.8 }, { nom: "Missy", km: 1.8 }, { nom: "Saint-Aubin", km: 2.2 }],
    },
    {
        slug: "cernier",
        name: "Cernier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.32465, lng: 7.22878 },
        top_places: ["Haute-Sorne", "Boécourt", "Rebévelier", "Montmelon"],
        zip: "2053",
        tier: 'HUB',
        zones: [{ nom: "Haute-Sorne", km: 2.0 }, { nom: "Boécourt", km: 3.0 }, { nom: "Rebévelier", km: 4.4 }, { nom: "Montmelon", km: 4.4 }],
    },
    {
        slug: "fontainemelon",
        name: "Fontainemelon",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.85426, lng: 6.59923 },
        top_places: ["Mauborget", "Tévenon", "Grandevent", "Fiez"],
        zip: "2052",
        tier: 'HUB',
        zones: [{ nom: "Mauborget", km: 1.6 }, { nom: "Tévenon", km: 2.2 }, { nom: "Grandevent", km: 2.3 }, { nom: "Fiez", km: 2.7 }],
    },
    {
        slug: "les-brenets",
        name: "Les Brenets",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.90978, lng: 7.12546 },
        top_places: ["Villars-les-Moines", "Meyriez", "Courgevaux", "Cressier"],
        zip: "2416",
        tier: 'HUB',
        zones: [{ nom: "Villars-les-Moines", km: 0.4 }, { nom: "Meyriez", km: 1.0 }, { nom: "Courgevaux", km: 1.1 }, { nom: "Cressier", km: 1.2 }],
    },
    {
        slug: "la-sagne",
        name: "La Sagne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.04891, lng: 6.80474 },
        top_places: ["Le Locle", "La Chaux-de-Fonds", "Les Planchettes", "Rochefort"],
        zip: "2314",
        tier: 'HUB',
        zones: [{ nom: "Le Locle", km: 4.3 }, { nom: "La Chaux-de-Fonds", km: 5.9 }, { nom: "Les Planchettes", km: 7.1 }, { nom: "Rochefort", km: 7.3 }],
    },
    {
        slug: "le-landeron",
        name: "Le Landeron",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.06347, lng: 7.06224 },
        top_places: ["Lignières", "La Neuveville", "Cressier", "Enges"],
        zip: "2525",
        tier: 'HUB',
        zones: [{ nom: "Lignières", km: 2.2 }, { nom: "La Neuveville", km: 2.4 }, { nom: "Cressier", km: 2.5 }, { nom: "Enges", km: 3.5 }],
    },
    {
        slug: "cressier",
        name: "Cressier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.89639, lng: 7.13991 },
        top_places: ["Guschelmuth", "Cormondes", "Villars-les-Moines", "Courgevaux"],
        zip: "2087",
        tier: 'HUB',
        zones: [{ nom: "Guschelmuth", km: 1.8 }, { nom: "Cormondes", km: 2.1 }, { nom: "Villars-les-Moines", km: 2.2 }, { nom: "Courgevaux", km: 2.4 }],
    },
    {
        slug: "hauterive",
        name: "Hauterive",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.76538, lng: 7.09849 },
        top_places: ["Matran", "Neyruz", "Villars-sur-Glâne", "Avry"],
        zip: "2068",
        tier: 'HUB',
        zones: [{ nom: "Matran", km: 2.1 }, { nom: "Neyruz", km: 2.4 }, { nom: "Villars-sur-Glâne", km: 2.4 }, { nom: "Avry", km: 3.1 }],
    },
    {
        slug: "saint-blaise",
        name: "Saint-Blaise",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.48375, lng: 6.91414 },
        top_places: ["Blonay – Saint-Légier", "Châtel-Saint-Denis", "Remaufens", "Jongny"],
        zip: "2072",
        tier: 'HUB',
        zones: [{ nom: "Blonay – Saint-Légier", km: 2.5 }, { nom: "Châtel-Saint-Denis", km: 4.9 }, { nom: "Remaufens", km: 5.2 }, { nom: "Jongny", km: 5.2 }],
    },
    {
        slug: "romont",
        name: "Romont",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.19838, lng: 7.32888 },
        top_places: ["Sauge", "Perles", "Longeau", "Meinisberg"],
        zip: "1680",
        tier: 'HUB',
        zones: [{ nom: "Sauge", km: 2.5 }, { nom: "Perles", km: 2.7 }, { nom: "Longeau", km: 3.4 }, { nom: "Meinisberg", km: 4.6 }],
    },
    {
        slug: "chatel-saint-denis",
        name: "Châtel-Saint-Denis",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.5199, lng: 6.94896 },
        top_places: ["Semsales", "Remaufens", "Maracon", "Blonay – Saint-Légier"],
        zip: "1618",
        tier: 'HUB',
        zones: [{ nom: "Semsales", km: 5.3 }, { nom: "Remaufens", km: 6.3 }, { nom: "Maracon", km: 6.9 }, { nom: "Blonay – Saint-Légier", km: 7.4 }],
    },
    {
        slug: "vaulruz",
        name: "Vaulruz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.60726, lng: 6.97036 },
        top_places: ["Sâles", "Vuadens", "La Verrerie", "Semsales"],
        zip: "1627",
        tier: 'HUB',
        zones: [{ nom: "Sâles", km: 2.9 }, { nom: "Vuadens", km: 3.7 }, { nom: "La Verrerie", km: 4.2 }, { nom: "Semsales", km: 5.3 }],
    },
    {
        slug: "riaz",
        name: "Riaz",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.64006, lng: 7.0565 },
        top_places: ["Marsens", "Echarlens", "Morlon", "Bulle"],
        zip: "1632",
        tier: 'HUB',
        zones: [{ nom: "Marsens", km: 1.4 }, { nom: "Echarlens", km: 1.7 }, { nom: "Morlon", km: 2.2 }, { nom: "Bulle", km: 2.6 }],
    },
    {
        slug: "broc",
        name: "Broc",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.59997, lng: 7.12209 },
        top_places: ["Botterens", "Crésuz", "Châtel-sur-Montsalvens", "Gruyères"],
        zip: "1636",
        tier: 'HUB',
        zones: [{ nom: "Botterens", km: 1.9 }, { nom: "Crésuz", km: 2.0 }, { nom: "Châtel-sur-Montsalvens", km: 2.0 }, { nom: "Gruyères", km: 3.6 }],
    },
    {
        slug: "gruyeres",
        name: "Gruyères",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.57223, lng: 7.04839 },
        top_places: ["Le Pâquier", "Bas-Intyamon", "Bulle", "Broc"],
        zip: "1663",
        tier: 'HUB',
        zones: [{ nom: "Le Pâquier", km: 2.5 }, { nom: "Bas-Intyamon", km: 2.7 }, { nom: "Bulle", km: 4.9 }, { nom: "Broc", km: 5.0 }],
    },
    {
        slug: "charmey",
        name: "Charmey",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.61842, lng: 7.19361 },
        top_places: ["Val-de-Charmey", "Crésuz", "Châtel-sur-Montsalvens", "Jaun"],
        zip: "1637",
        tier: 'HUB',
        zones: [{ nom: "Val-de-Charmey", km: 2.2 }, { nom: "Crésuz", km: 4.6 }, { nom: "Châtel-sur-Montsalvens", km: 4.6 }, { nom: "Jaun", km: 5.6 }],
    },
    {
        slug: "villars-sur-glane",
        name: "Villars-sur-Glâne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.79625, lng: 7.12305 },
        top_places: ["Corminboeuf", "Fribourg", "Givisiez", "Matran"],
        zip: "1752",
        tier: 'HUB',
        zones: [{ nom: "Corminboeuf", km: 1.8 }, { nom: "Fribourg", km: 2.1 }, { nom: "Givisiez", km: 2.4 }, { nom: "Matran", km: 2.8 }],
    },
    {
        slug: "marly",
        name: "Marly",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.7768, lng: 7.14736 },
        top_places: ["Villarsel-sur-Marly", "Villars-sur-Glâne", "Bois-d'Amont", "Fribourg"],
        zip: "1723",
        tier: 'HUB',
        zones: [{ nom: "Villarsel-sur-Marly", km: 1.9 }, { nom: "Villars-sur-Glâne", km: 2.4 }, { nom: "Bois-d'Amont", km: 2.5 }, { nom: "Fribourg", km: 2.6 }],
    },
    {
        slug: "grolley",
        name: "Grolley",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.82803, lng: 7.06167 },
        top_places: ["Grolley-Ponthaux", "Misery-Courtion", "Ponthaux", "Belfaux"],
        zip: "1772",
        tier: 'HUB',
        zones: [{ nom: "Grolley-Ponthaux", km: 0.7 }, { nom: "Misery-Courtion", km: 2.5 }, { nom: "Ponthaux", km: 2.5 }, { nom: "Belfaux", km: 2.5 }],
    },
    {
        slug: "corminboeuf",
        name: "Corminboeuf",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.80135, lng: 7.09475 },
        top_places: ["Matran", "Villars-sur-Glâne", "Avry", "Belfaux"],
        zip: "1720",
        tier: 'HUB',
        zones: [{ nom: "Matran", km: 2.0 }, { nom: "Villars-sur-Glâne", km: 2.6 }, { nom: "Avry", km: 2.9 }, { nom: "Belfaux", km: 3.0 }],
    },
    {
        slug: "matran",
        name: "Matran",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.78464, lng: 7.09296 },
        top_places: ["Corminboeuf", "Villars-sur-Glâne", "Avry", "Hauterive"],
        zip: "1754",
        tier: 'HUB',
        zones: [{ nom: "Corminboeuf", km: 1.8 }, { nom: "Villars-sur-Glâne", km: 1.8 }, { nom: "Avry", km: 2.0 }, { nom: "Hauterive", km: 2.7 }],
    },
    {
        slug: "saint-ursanne",
        name: "Saint-Ursanne",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 46.78787, lng: 7.22892 },
        top_places: ["Saint-Ours", "Rechthalten", "Tavel", "Tentlingen"],
        zip: "2882",
        tier: 'HUB',
        zones: [{ nom: "Saint-Ours", km: 0.4 }, { nom: "Rechthalten", km: 3.0 }, { nom: "Tavel", km: 3.2 }, { nom: "Tentlingen", km: 3.2 }],
    },
    {
        slug: "saignelegier",
        name: "Saignelégier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.26388, lng: 6.97608 },
        top_places: ["Muriaux", "Le Bémont", "Montfaucon", "Montfaucon"],
        zip: "2350",
        tier: 'HUB',
        zones: [{ nom: "Muriaux", km: 1.6 }, { nom: "Le Bémont", km: 3.1 }, { nom: "Montfaucon", km: 5.9 }, { nom: "Montfaucon", km: 6.0 }],
    },
    {
        slug: "les-breuleux",
        name: "Les Breuleux",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.21186, lng: 7.00859 },
        top_places: ["Mont-Tramelan", "Saignelégier", "Muriaux", "Le Noirmont"],
        zip: "2345",
        tier: 'HUB',
        zones: [{ nom: "Mont-Tramelan", km: 3.4 }, { nom: "Saignelégier", km: 4.3 }, { nom: "Muriaux", km: 4.7 }, { nom: "Le Noirmont", km: 4.9 }],
    },
    {
        slug: "le-noirmont",
        name: "Le Noirmont",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.2114, lng: 6.94076 },
        top_places: ["Les Bois", "Les Breuleux", "Muriaux", "Saignelégier"],
        zip: "2340",
        tier: 'HUB',
        zones: [{ nom: "Les Bois", km: 4.4 }, { nom: "Les Breuleux", km: 4.7 }, { nom: "Muriaux", km: 5.4 }, { nom: "Saignelégier", km: 6.2 }],
    },
    {
        slug: "alle",
        name: "Alle",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.42765, lng: 7.12632 },
        top_places: ["Vendlincourt", "Courgenay", "La Baroche", "Porrentruy"],
        zip: "2942",
        tier: 'HUB',
        zones: [{ nom: "Vendlincourt", km: 3.1 }, { nom: "Courgenay", km: 3.1 }, { nom: "La Baroche", km: 3.3 }, { nom: "Porrentruy", km: 3.5 }],
    },
    {
        slug: "boncourt",
        name: "Boncourt",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.48521, lng: 7.00434 },
        top_places: ["Basse-Allaine", "Bure", "Courchavon", "Damphreux-Lugnez"],
        zip: "2926",
        tier: 'HUB',
        zones: [{ nom: "Basse-Allaine", km: 4.5 }, { nom: "Bure", km: 5.2 }, { nom: "Courchavon", km: 6.7 }, { nom: "Damphreux-Lugnez", km: 7.1 }],
    },
    {
        slug: "courgenay",
        name: "Courgenay",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.39235, lng: 7.1244 },
        top_places: ["Fontenais", "Cornol", "Alle", "Porrentruy"],
        zip: "2950",
        tier: 'HUB',
        zones: [{ nom: "Fontenais", km: 3.2 }, { nom: "Cornol", km: 3.3 }, { nom: "Alle", km: 3.7 }, { nom: "Porrentruy", km: 4.1 }],
    },
    {
        slug: "bassecourt",
        name: "Bassecourt",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.56159, lng: 9.03999 },
        top_places: ["Amlikon-Bissegg", "Bussnang", "Wigoltingen", "Märstetten"],
        zip: "2854",
        tier: 'HUB',
        zones: [{ nom: "Amlikon-Bissegg", km: 0.9 }, { nom: "Bussnang", km: 3.3 }, { nom: "Wigoltingen", km: 3.8 }, { nom: "Märstetten", km: 4.7 }],
    },
    {
        slug: "vicques",
        name: "Vicques",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 45.93457, lng: 8.92642 },
        top_places: ["Vico Morcote", "Brusino Arsizio", "Morcote", "Melide"],
        zip: "2824",
        tier: 'HUB',
        zones: [{ nom: "Vico Morcote", km: 0.8 }, { nom: "Brusino Arsizio", km: 1.2 }, { nom: "Morcote", km: 1.3 }, { nom: "Melide", km: 2.5 }],
    },
    {
        slug: "moutier",
        name: "Moutier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.27689, lng: 7.37096 },
        top_places: ["Eschert", "Perrefitte", "Belprahon", "Roches"],
        zip: "2740",
        tier: 'HUB',
        zones: [{ nom: "Eschert", km: 2.2 }, { nom: "Perrefitte", km: 2.2 }, { nom: "Belprahon", km: 2.9 }, { nom: "Roches", km: 3.0 }],
    },
    {
        slug: "la-neuveville",
        name: "La Neuveville",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.07402, lng: 7.09697 },
        top_places: ["Lignières", "Gléresse", "Le Landeron", "Cerlier"],
        zip: "2520",
        tier: 'HUB',
        zones: [{ nom: "Lignières", km: 2.5 }, { nom: "Gléresse", km: 2.9 }, { nom: "Le Landeron", km: 3.0 }, { nom: "Cerlier", km: 3.5 }],
    },
    {
        slug: "tavannes",
        name: "Tavannes",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.21937, lng: 7.1793 },
        top_places: ["Sonceboz-Sombeval", "Saicourt", "Reconvilier", "Saules"],
        zip: "2710",
        tier: 'HUB',
        zones: [{ nom: "Sonceboz-Sombeval", km: 2.5 }, { nom: "Saicourt", km: 3.5 }, { nom: "Reconvilier", km: 3.7 }, { nom: "Saules", km: 4.2 }],
    },
    {
        slug: "saint-imier",
        name: "Saint-Imier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.15261, lng: 6.99112 },
        top_places: ["Villeret", "Sonvilier", "Cormoret", "Renan"],
        zip: "2610",
        tier: 'HUB',
        zones: [{ nom: "Villeret", km: 2.3 }, { nom: "Sonvilier", km: 2.4 }, { nom: "Cormoret", km: 5.5 }, { nom: "Renan", km: 5.7 }],
    },
    {
        slug: "courtelary",
        name: "Courtelary",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.17373, lng: 7.08008 },
        top_places: ["Cortébert", "Cormoret", "Mont-Tramelan", "Corgémont"],
        zip: "2608",
        tier: 'HUB',
        zones: [{ nom: "Cortébert", km: 1.8 }, { nom: "Cormoret", km: 1.9 }, { nom: "Mont-Tramelan", km: 4.6 }, { nom: "Corgémont", km: 4.8 }],
    },
    {
        slug: "tramelan",
        name: "Tramelan",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.22736, lng: 7.09682 },
        top_places: ["Mont-Tramelan", "Les Genevez", "Cortébert", "Corgémont"],
        zip: "2720",
        tier: 'HUB',
        zones: [{ nom: "Mont-Tramelan", km: 3.7 }, { nom: "Les Genevez", km: 3.7 }, { nom: "Cortébert", km: 4.9 }, { nom: "Corgémont", km: 5.1 }],
    },
    {
        slug: "corgemont",
        name: "Corgémont",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.1867, lng: 7.13946 },
        top_places: ["Cortébert", "Sonceboz-Sombeval", "Tramelan", "Courtelary"],
        zip: "2606",
        tier: 'HUB',
        zones: [{ nom: "Cortébert", km: 3.0 }, { nom: "Sonceboz-Sombeval", km: 3.2 }, { nom: "Tramelan", km: 5.0 }, { nom: "Courtelary", km: 5.2 }],
    },
    {
        slug: "sonceboz-sombeval",
        name: "Sonceboz-Sombeval",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.19105, lng: 7.17875 },
        top_places: ["Corgémont", "Tavannes", "Orvin", "Péry-La Heutte"],
        zip: "2605",
        tier: 'HUB',
        zones: [{ nom: "Corgémont", km: 3.0 }, { nom: "Tavannes", km: 3.7 }, { nom: "Orvin", km: 4.3 }, { nom: "Péry-La Heutte", km: 5.4 }],
    },
    {
        slug: "reconvilier",
        name: "Reconvilier",
        heroTitle: "Panneaux Solaires",
        geo: { lat: 47.22482, lng: 7.22805 },
        top_places: ["Tavannes", "Loveresse", "Saules", "Saicourt"],
        zip: "2732",
        tier: 'HUB',
        zones: [{ nom: "Tavannes", km: 2.1 }, { nom: "Loveresse", km: 2.1 }, { nom: "Saules", km: 2.4 }, { nom: "Saicourt", km: 2.7 }],
    },
];

// Helper to get a target by slug
export function getTargetBySlug(slug: string): NationalTarget | undefined {
    return NATIONAL_TARGETS.find(t => t.slug === slug);
}

// ========================================
// ADAPTER: Convert NationalTarget to CityConfig
// Uses pSEO for unique content per city
// ========================================
import { CityConfig } from "@/lib/db";
import { CANTONS, cantonFromNpa } from "@/data/ch-cantons";

export function getTargetAsCityConfig(slug: string): CityConfig | undefined {
    const target = NATIONAL_TARGETS.find(t => t.slug === slug);
    if (!target) return undefined;

    const priceDisplay = "Sur Devis";
    const priceDesc = "Étude & Devis Solaire Gratuit";

    const title = `Installateur Panneaux Solaires ${target.name} | Devis & Aides Les Pros du Solaire`;
    const uniqueDescription = `Trouvez votre installateur Les Pros du Solaire de panneaux solaires à ${target.name} (${target.zip}). Réalisez des économies d'énergie en autoconsommation. Devis gratuit sous 24h.`;
    const uniqueMetaDescription = `Installation panneaux solaires photovoltaïques ${target.name}. Devis gratuit sous 24h avec des poseurs Les Pros du Solaire. Rétribution unique déduite.`;

    return {
        slug: target.slug,
        city: target.name,
        name: `Solaire ${target.name}`,
        domain: `expertpanneausolaire.ch/ville/${target.slug}`,
        heroImage: target.heroImage || "/images/generated/solar-hero.webp",

        postalCode: target.zip,
        // `department` = code canton (utilisé par le maillage interne)
        department: cantonFromNpa(target.zip) || "CH",
        // Nom du canton réel (auparavant codé en dur sur "Suisse")
        region: CANTONS[cantonFromNpa(target.zip) || ""]?.name || "Suisse romande",

        description: uniqueDescription,
        geo: target.geo,
        unique_intro: target.unique_intro,

        features: [
            "Primes Déduites",
            "Rendement Garanti",
            "Les Pros du Solaire",
            "Matériel 25 ans",
            "Devis sous 24h"
        ],

        stations: [],
        hospitals: [],
        // Zones d'intervention : communes limitrophes réelles, jamais des quartiers inventés
        neighborhoods: target.top_places,
        zones: target.zones,

        points_of_interest: {
            hotels: [],
            nightlife: [],
            monuments: [],
            parking_difficulty: "High Demand"
        },

        pricing: {
            base: priceDisplay,
            description: priceDesc,
            km: 0
        },

        phoneNumber: "+41 22 000 00 00",
        email: "contact@expertpanneausolaire.ch",
        type: "PARTNER",
        targetType: "MIXED",

        meta: {
            title,
            description: uniqueMetaDescription
        }
    };
}

